version: '3'

networks:
  ds_net:
    external:
      name: ds_net

services:

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - ds_net
    environment:
      - NODE_ENV=development